### ISSUE TITLE
How to see frequently-used commands?

### ISSUE THREAD

**Issue by UlyssesZh** [YiNNx/cmd-wrapped#21]
> as well as frequently-used commands over the past years.

Where is this feature?

**Comment by YiNNx** [comment]
On the forth page:

![image](https://github.com/YiNNx/cmd-wrapped/assets/86649490/57f39e61-7371-4ec9-805c-52caf3b75972)

 It analyzes your frequently-used commands in a specific year.

**Comment by UlyssesZh** [comment]
Didn't notice there are multiple pages. Thanks!
