### ISSUE TITLE
Some errors on Manjaro Linux

### ISSUE THREAD

**Issue by ericzhang-debug** [YiNNx/cmd-wrapped#37]
Hello, I meet some errors on Manjaro Linux(Arch Linux). It said that the model of "OS" was not found. I tried to install via AUR and had tried the cmd-wrapped and cmd-wrapped-bin.
Bellow is error log:
![image](https://github.com/user-attachments/assets/fd327a10-36a9-49de-9713-27e067548a06)

Bellow is system information of my computer:
![image](https://github.com/user-attachments/assets/2f1143e2-0396-47d2-8df4-641f7e4101dc)

Thank you!

**Comment by YiNNx** [comment]
What's the output of `cmd-wrapped --version` and `echo $HISTFILE` ?

**Comment by ericzhang-debug** [comment]
![image](https://github.com/user-attachments/assets/a3e06736-daec-44ca-b327-53df445607d1)

**Comment by YiNNx** [comment]
It looks like your `/home/eric/.zhistory` file do not exist :thinking: 

![image](https://github.com/user-attachments/assets/43afc279-89ca-45cb-b3db-b74c9e0b37c3)

**Comment by ericzhang-debug** [comment]
But my shell was bash and it showed the same error when I execute ```cmd-wrapped -s bash```. When I execute ```history``` , it showed something rigth.

**Comment by YiNNx** [comment]
> ![image](https://private-user-images.githubusercontent.com/71204348/365197775-a3e06736-daec-44ca-b327-53df445607d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzM3MjQsIm5iZiI6MTcyNTYzMzQyNCwicGF0aCI6Ii83MTIwNDM0OC8zNjUxOTc3NzUtYTNlMDY3MzYtZGFlYy00NGNhLWIzMjctNTNkZjQ0NTYwN2QxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE0MzcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxZTQzNjE0NDU3ZWMzZTU0NGMwOWJkZWIwNTY1NDNlYjI3MGU3NzVkZjJkNjM4MzYzYWQ4YTVjODc3YmEyZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p83zdeyq7371zkWBbntd1EsS3ni2mSJrhd9xSETAXjY)

Seems like you have set your bash history file as `/home/eric/.zhistory`, and the file path do not exist. 
Both check your `/home/eric/.zhistory` and `/home/eric/.bash_history`

**Comment by ericzhang-debug** [comment]
Both are not existed.

**Comment by YiNNx** [comment]
> Both are not existed.

It looks like there’s an issue with your shell history persistence settings. To fix this, you’ll need to make sure that $HISTFILE is pointing to the right history file path.

See https://www.gnu.org/software/bash/manual/html_node/Bash-History-Facilities.html

> When the shell starts up, the history is initialized from the file named by the HISTFILE variable (default ~/.bash_history)... **If HISTFILE is unset, or if the history file is unwritable, the history is not saved.**

This error isn’t related to cmd-wrapped, so I’ll go ahead and close this issue. Thanks for your patience!
